/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "all_gate.v:1" *)
module all_gate(a, b, and1, or1, xor1, nand1, nor1, xnor1);
  (* src = "all_gate.v:2" *)
  input a;
  (* src = "all_gate.v:3" *)
  output and1;
  (* src = "all_gate.v:2" *)
  input b;
  (* src = "all_gate.v:3" *)
  output nand1;
  (* src = "all_gate.v:3" *)
  output nor1;
  (* src = "all_gate.v:3" *)
  output or1;
  (* src = "all_gate.v:3" *)
  output xnor1;
  (* src = "all_gate.v:3" *)
  output xor1;
  assign or1 = b | a;
  assign nor1 = ~(b | a);
  assign and1 = b & a;
  assign nand1 = ~(b & a);
  assign xor1 = b ^ a;
  assign xnor1 = ~(b ^ a);
endmodule
