/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "all_gate.v:1" *)
module all_gate(a, b, and1, or1, xor1, nand1, nor1, xnor1);
  (* src = "all_gate.v:2" *)
  wire _00_;
  (* src = "all_gate.v:3" *)
  wire _01_;
  (* src = "all_gate.v:2" *)
  wire _02_;
  (* src = "all_gate.v:3" *)
  wire _03_;
  (* src = "all_gate.v:3" *)
  wire _04_;
  (* src = "all_gate.v:3" *)
  wire _05_;
  (* src = "all_gate.v:3" *)
  wire _06_;
  (* src = "all_gate.v:3" *)
  wire _07_;
  (* src = "all_gate.v:2" *)
  input a;
  (* src = "all_gate.v:3" *)
  output and1;
  (* src = "all_gate.v:2" *)
  input b;
  (* src = "all_gate.v:3" *)
  output nand1;
  (* src = "all_gate.v:3" *)
  output nor1;
  (* src = "all_gate.v:3" *)
  output or1;
  (* src = "all_gate.v:3" *)
  output xnor1;
  (* src = "all_gate.v:3" *)
  output xor1;
  sky130_fd_sc_hd__nor2_1 _08_ (
    .A(_02_),
    .B(_00_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _09_ (
    .A(_02_),
    .SLEEP(_00_),
    .X(_05_)
  );
  sky130_fd_sc_hd__and2_0 _10_ (
    .A(_02_),
    .B(_00_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _11_ (
    .A(_02_),
    .B(_00_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(_02_),
    .B(_00_),
    .X(_07_)
  );
  sky130_fd_sc_hd__xnor2_1 _13_ (
    .A(_02_),
    .B(_00_),
    .Y(_06_)
  );
  assign _02_ = b;
  assign _00_ = a;
  assign or1 = _05_;
  assign nor1 = _04_;
  assign and1 = _01_;
  assign nand1 = _03_;
  assign xor1 = _07_;
  assign xnor1 = _06_;
endmodule
