/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "and1.v:1" *)
module and1(in1, in2, out1);
  (* src = "and1.v:2" *)
  input in1;
  (* src = "and1.v:3" *)
  input in2;
  (* src = "and1.v:4" *)
  output out1;
  assign out1 = in2 & in1;
endmodule
