/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "and1.v:1" *)
module and1(in1, in2, out1);
  (* src = "and1.v:2" *)
  wire _0_;
  (* src = "and1.v:3" *)
  wire _1_;
  (* src = "and1.v:4" *)
  wire _2_;
  (* src = "and1.v:2" *)
  input in1;
  (* src = "and1.v:3" *)
  input in2;
  (* src = "and1.v:4" *)
  output out1;
  AND2_X1 _3_ (
    .A1(_1_),
    .A2(_0_),
    .Z(_2_)
  );
  assign _1_ = in2;
  assign _0_ = in1;
  assign out1 = _2_;
endmodule
