/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "xorgate.v:1" *)
module xorgate(in1, in2, out1);
  (* src = "xorgate.v:2" *)
  input in1;
  (* src = "xorgate.v:2" *)
  input in2;
  (* src = "xorgate.v:3" *)
  output out1;
  assign out1 = in2 ^ in1;
endmodule
